---
remotes:
  vendor: https://github.com/sstephenson/rbenv
  primary: git@github.com:destructuring/rbenv
  secondary: git@bitbucket.org:destructuring/rbenv
  sh: https://github.com/destructuring/jason
